name: Build Vulkan VirtIO Venus Termux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout o código-fonte do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Baixar o script diretamente do repositório GitHub
      - name: Download the build script
        run: |
          curl -o virtio-venus-builder.sh https://raw.githubusercontent.com/Guilhermepr0jetos/vulkan-virtio-venus-termux/master/virtio-venus-builder.sh
          chmod +x virtio-venus-builder.sh

      # Executar o script baixado
      - name: Run the build script
        run: |
          ./virtio-venus-builder.sh
